"""Tests for the T-Mobile activation-first flow.

Covers:
  * activate_subscriber() builds the EXACT nested baseProduct payload T-Mobile
    requires ({iccid, marketZip, language, baseProduct{baseProductId, wps,
    product[]}}) with NO accountId and NO msisdn, sends the call-back-location
    header, and falls back to env / PIT constants.
  * activate_subscriber() validates required inputs.
  * activate_subscriber() refuses to send unless TMOBILE_PIT_LIVE_CALLS_ENABLED.
  * subscriber_inquiry() needs no account ID (that requirement was never in the
    vendor contract) and is stopped only by the live-send boundary.
  * the callback processor captures a generated account ID + assigned
    MSISDN (pure helpers — no DB, per the house test pattern).

No real T-Mobile credentials: the RSA key is generated and HTTP is mocked.
OAuth/PoP code is exercised but not modified.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from types import SimpleNamespace

import httpx
import pytest
import respx
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

import app.integrations.tmobile_operations as ops
import app.integrations.tmobile_taap as taap
from app.services.tmobile_callback_processor import (
    extract_signal,
    merge_activation_identifiers,
)

TOKEN_URL = "https://pit-oauth.t-mobile.com/oauth2/v2/tokens"
BASE_URL = "https://pit-apis.t-mobile.com"
# Default subscriber base path is the PIT gateway's /wholesale/v1/subscriber.
ACTIVATE_PATH = "/wholesale/v1/subscriber/activation"
ACTIVATE_URL = f"{BASE_URL}{ACTIVATE_PATH}"


@pytest.fixture
def tmobile_env(monkeypatch):
    """Generated RSA key + mocked T-Mobile settings (creds, hosts, activation env)."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    monkeypatch.setattr(taap, "_load_private_key", lambda: pem)
    for name, value in {
        "TMOBILE_ENV": "pit",
        "TMOBILE_BASE_URL": BASE_URL,
        "TMOBILE_TOKEN_URL": TOKEN_URL,
        "TMOBILE_CONSUMER_KEY": "ck",
        "TMOBILE_CONSUMER_SECRET": "cs",
        "TMOBILE_PARTNER_ID": "128",
        "TMOBILE_SENDER_ID": "128",
        "TMOBILE_ACCOUNT_ID": "",          # not available yet — generated by activation
        "TMOBILE_PRODUCT_ID": "PID-ENV",   # legacy flat field — unused by the nested body
        "TMOBILE_MARKET_ZIP": "30338",
        "TMOBILE_LANGUAGE": "ENGL",
        "TMOBILE_BASE_PRODUCT_ID": "",     # blank -> PIT constant "Infatrac Internet Access Plan"
        "TMOBILE_WPS": "",                 # blank -> PIT constant "00011586"
        "TMOBILE_CALLBACK_LOCATION": "https://pit-api.example.com/tmobile/wholesale/callback",
        # Live PIT calls authorized in the fixture so the send-path tests exercise
        # the wire request; the disabled-by-default behavior has its own test.
        "TMOBILE_PIT_LIVE_CALLS_ENABLED": "true",
    }.items():
        monkeypatch.setattr(f"app.config.settings.{name}", value)


def _mock_token_and_activate():
    respx.post(TOKEN_URL).mock(return_value=httpx.Response(
        200, json={"access_token": "tok", "expires_in": 3600}))
    respx.post(ACTIVATE_URL).mock(return_value=httpx.Response(
        200, json={"status": "accepted"}))


def _activate_request(path: str = ACTIVATE_PATH):
    for call in respx.calls:
        if call.request.url.path == path:
            return call.request
    raise AssertionError("activation request was not sent")


# ── activate_subscriber payload / headers ────────────────────────────
class TestActivateSubscriber:
    @respx.mock
    @pytest.mark.asyncio
    async def test_payload_has_no_accountid_or_msisdn(self, tmobile_env):
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(
            iccid="8901240204219433645", market_zip="30346",
            callback_location="https://cb.example/hook")
        await client.close()

        req = _activate_request()
        body = json.loads(req.content)
        # Nested baseProduct body — exactly T-Mobile's required shape.
        assert body == {
            "iccid": "8901240204219433645",
            "marketZip": "30346",
            "language": "ENGL",
            "baseProduct": {
                "baseProductId": "Infatrac Internet Access Plan",
                "wps": "00011586",
                "product": [
                    {"ProductID": "NOROAM", "isBaseProduct": False, "action": "ADD"},
                ],
            },
        }
        assert "accountId" not in body
        assert "msisdn" not in body
        assert req.headers["call-back-location"] == "https://cb.example/hook"
        # Infatrac sender/partner = 128 (applied by _request from env).
        # T-Mobile requires the lowercase header names "sender-id" / "partner-id".
        assert req.headers["sender-id"] == "128"
        assert req.headers["partner-id"] == "128"
        # No account header while account ID is unknown.
        assert "X-Account-Id" not in req.headers

    @respx.mock
    @pytest.mark.asyncio
    async def test_falls_back_to_env(self, tmobile_env):
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(iccid="8901240204219433652")
        await client.close()

        req = _activate_request()
        body = json.loads(req.content)
        assert body["marketZip"] == "30338"        # TMOBILE_MARKET_ZIP
        assert body["language"] == "ENGL"          # TMOBILE_LANGUAGE
        # baseProductId/wps blank in env -> PIT constants.
        assert body["baseProduct"]["baseProductId"] == "Infatrac Internet Access Plan"
        assert body["baseProduct"]["wps"] == "00011586"
        assert req.headers["call-back-location"].endswith("/tmobile/wholesale/callback")

    @respx.mock
    @pytest.mark.asyncio
    async def test_disabled_by_default_refuses_to_send(self, tmobile_env, monkeypatch):
        # The live feature flag is the hard gate: with it off, activation must
        # raise and never open a socket.
        monkeypatch.setattr("app.config.settings.TMOBILE_PIT_LIVE_CALLS_ENABLED", "false")
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        with pytest.raises(RuntimeError, match="TMOBILE_PIT_LIVE_CALLS_ENABLED"):
            await client.activate_subscriber(
                iccid="8901240204219433645", market_zip="30346",
                callback_location="https://cb.example/hook")
        await client.close()
        # Nothing was sent — the activation endpoint was never called.
        assert not any(c.request.url.path == ACTIVATE_PATH for c in respx.calls)

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_iccid(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="ICCID"):
            await client.activate_subscriber(iccid="")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_base_product_and_wps(self, tmobile_env, monkeypatch):
        # Blank both env AND the PIT constant fallback so the guards can fire.
        monkeypatch.setattr(taap, "PIT_BASE_PRODUCT_ID", "")
        monkeypatch.setattr(taap, "PIT_WPS", "")
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="baseProductId"):
            await client.activate_subscriber(iccid="89012", market_zip="30338")
        # baseProductId provided, wps still blank -> wps guard fires.
        with pytest.raises(ValueError, match="wps"):
            await client.activate_subscriber(
                iccid="89012", market_zip="30338", base_product_id="Infatrac")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_market_zip(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_MARKET_ZIP", "")
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="marketZip"):
            await client.activate_subscriber(iccid="89012", market_zip="")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_callback_location(self, tmobile_env, monkeypatch):
        # The account ID comes back ONLY via the callback — activation must
        # refuse to send without one rather than strand the generated ID.
        monkeypatch.setattr("app.config.settings.TMOBILE_CALLBACK_LOCATION", "")
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="call-back-location"):
            await client.activate_subscriber(
                iccid="8901240204219433645", market_zip="30346",
                callback_location="")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_callback_location_on_wire(self, tmobile_env):
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(
            iccid="8901240204219433645", market_zip="30346",
            callback_location="  https://cb.example/hook  ")
        await client.close()
        req = _activate_request()
        # Required header is present and stripped of stray whitespace.
        assert req.headers["call-back-location"] == "https://cb.example/hook"


# ── env-driven resource paths ────────────────────────────────────────
class TestEnvDrivenPaths:
    def test_default_subscriber_base_is_v1(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        # PIT gateway URL list uses /wholesale/v1/subscriber (not subscriber/v2).
        assert client.subscriber_base_path == "/wholesale/v1/subscriber"
        assert client.activation_endpoint() == "/wholesale/v1/subscriber/activation"

    def test_activation_path_env_override(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_ACTIVATION_PATH",
                            "/wholesale/v1/activation/submit")
        client = taap.TMobileTAAPClient()
        # Explicit activation override wins; subscriber base is unaffected.
        assert client.activation_endpoint() == "/wholesale/v1/activation/submit"

    def test_subscriber_base_override_no_longer_moves_activation(
        self, tmobile_env, monkeypatch
    ):
        """Changing the base path must NOT relocate the activation route.

        It used to: the fallback derived ``{base}/activate``, which is a route
        that does not exist. Activation only ever worked because the explicit
        override happened to be set. The fallback is now the registry's exact
        vendor-confirmed path, so a base-path change cannot silently point
        activation somewhere wrong.
        """
        monkeypatch.setattr("app.config.settings.TMOBILE_SUBSCRIBER_BASE_PATH",
                            "/wholesale/subscriber/v2")
        client = taap.TMobileTAAPClient()

        assert client.activation_endpoint() == "/wholesale/v1/subscriber/activation"

    def test_trailing_slash_is_normalized(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_SUBSCRIBER_BASE_PATH",
                            "/wholesale/v1/subscriber/")
        client = taap.TMobileTAAPClient()
        assert client._subscriber_path("activate") == "/wholesale/v1/subscriber/activate"
        # NOTE: _subscriber_path still joins strings, but no operation resolves
        # its wire path through it any more — see tmobile_operations.

    @respx.mock
    @pytest.mark.asyncio
    async def test_activation_uses_override_path_on_wire(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_ACTIVATION_PATH",
                            "/wholesale/v1/activation/submit")
        respx.post(TOKEN_URL).mock(return_value=httpx.Response(
            200, json={"access_token": "tok", "expires_in": 3600}))
        respx.post(f"{BASE_URL}/wholesale/v1/activation/submit").mock(
            return_value=httpx.Response(200, json={"status": "accepted"}))
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(iccid="8901240204219433645",
                                         market_zip="30346")
        await client.close()
        req = _activate_request("/wholesale/v1/activation/submit")
        assert json.loads(req.content)["iccid"] == "8901240204219433645"


# ── dry-run preview (no network, redacted secrets) ───────────────────
class TestActivationPreview:
    def test_preview_payload_and_safe_headers(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(
            iccid="8901260963132697538", market_zip="30346",
            callback_location="https://cb.example/hook")

        assert preview["method"] == "POST"
        assert preview["would_send"] is False
        assert preview["path"] == "/wholesale/v1/subscriber/activation"
        assert preview["url"].endswith("/wholesale/v1/subscriber/activation")
        assert preview["payload"] == {
            "iccid": "8901260963132697538",
            "marketZip": "30346",
            "language": "ENGL",
            "baseProduct": {
                "baseProductId": "Infatrac Internet Access Plan",
                "wps": "00011586",
                "product": [
                    {"ProductID": "NOROAM", "isBaseProduct": False, "action": "ADD"},
                ],
            },
        }
        # Secret-bearing headers must be redacted placeholders, never real values.
        assert "redacted" in preview["headers"]["Authorization"].lower()
        assert "redacted" in preview["headers"]["X-Authorization"].lower()
        assert "Bearer " not in preview["headers"]["Authorization"]
        # Non-sensitive headers are real.
        assert preview["headers"]["sender-id"] == "128"
        assert preview["headers"]["partner-id"] == "128"
        assert preview["headers"]["call-back-location"] == "https://cb.example/hook"

    def test_preview_falls_back_to_env(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(iccid="8901260963132697538")
        assert preview["payload"]["marketZip"] == "30338"   # TMOBILE_MARKET_ZIP
        assert preview["payload"]["language"] == "ENGL"     # TMOBILE_LANGUAGE
        assert preview["payload"]["baseProduct"]["wps"] == "00011586"  # PIT constant

    def test_preview_validates_inputs(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="ICCID"):
            client.build_activation_preview(iccid="")

    def test_preview_surfaces_missing_callback(self, tmobile_env, monkeypatch):
        # Dry-run must SHOW the gap, not raise — it's how operators detect a
        # missing callback before going live.
        monkeypatch.setattr("app.config.settings.TMOBILE_CALLBACK_LOCATION", "")
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(iccid="8901260963132697538")
        assert preview["callback_location_configured"] is False
        assert "call-back-location" in preview["headers"]
        assert "NOT SET" in preview["headers"]["call-back-location"]
        assert any("call-back-location is NOT configured" in n for n in preview["notes"])

    def test_preview_shows_configured_callback(self, tmobile_env):
        client = taap.TMobileTAAPClient()  # fixture sets TMOBILE_CALLBACK_LOCATION
        preview = client.build_activation_preview(iccid="8901260963132697538")
        assert preview["callback_location_configured"] is True
        assert preview["headers"]["call-back-location"].endswith("/tmobile/wholesale/callback")
        assert not any("NOT configured" in n for n in preview["notes"])

    def test_preview_makes_no_http_calls(self, tmobile_env):
        # respx is NOT active here; if the preview opened a socket this would
        # hit the network. It must stay purely local.
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(iccid="8901260963132697538")
        assert preview["would_send"] is False

    def test_preview_surfaces_live_flag_disabled(self, tmobile_env, monkeypatch):
        # Dry-run must SHOW whether live calls are armed (but never block).
        monkeypatch.setattr("app.config.settings.TMOBILE_PIT_LIVE_CALLS_ENABLED", "false")
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(iccid="8901260963132697538")
        assert preview["live_calls_enabled"] is False
        assert any("DISABLED" in n for n in preview["notes"])


# ── exact-structure pin against T-Mobile's provided activation sample ─
class TestActivationPayloadMatchesTMobileSample:
    # The verbatim activation sample T-Mobile supplied for PIT (sender/partner
    # 128). The wrapper must reproduce this byte-for-byte from an ICCID + the
    # PIT-safe config defaults.
    TMOBILE_SAMPLE = {
        "iccid": "8901260963132697538",
        "marketZip": "30346",
        "language": "ENGL",
        "baseProduct": {
            "baseProductId": "Infatrac Internet Access Plan",
            "wps": "00011586",
            "product": [
                {"ProductID": "NOROAM", "isBaseProduct": False, "action": "ADD"},
            ],
        },
    }

    def test_builder_matches_sample_from_defaults(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        payload = client._build_activation_payload(
            self.TMOBILE_SAMPLE["iccid"], market_zip="30346")
        assert payload == self.TMOBILE_SAMPLE

    def test_pit_constants_match_sample(self):
        # The PIT-safe constants ARE the sample's fixed values.
        assert taap.PIT_LANGUAGE == "ENGL"
        assert taap.PIT_BASE_PRODUCT_ID == "Infatrac Internet Access Plan"
        assert taap.PIT_WPS == "00011586"
        assert "30346" in taap.PIT_MARKET_ZIPS and "30338" in taap.PIT_MARKET_ZIPS
        assert list(taap.PIT_DEFAULT_PRODUCTS) == [
            {"ProductID": "NOROAM", "isBaseProduct": False, "action": "ADD"},
        ]

    @respx.mock
    @pytest.mark.asyncio
    async def test_wire_body_matches_sample(self, tmobile_env):
        # End-to-end: the bytes actually sent equal the sample exactly.
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(
            iccid=self.TMOBILE_SAMPLE["iccid"], market_zip="30346",
            callback_location="https://cb.example/hook")
        await client.close()
        req = _activate_request()
        assert json.loads(req.content) == self.TMOBILE_SAMPLE

    def test_default_products_not_mutated_across_calls(self, tmobile_env):
        # The builder must deep-copy PIT_DEFAULT_PRODUCTS so a caller mutating
        # the returned list can never poison the next activation.
        client = taap.TMobileTAAPClient()
        p1 = client._build_activation_payload("89010000000000001", market_zip="30346")
        p1["baseProduct"]["product"][0]["action"] = "REMOVE"
        p2 = client._build_activation_payload("89010000000000002", market_zip="30338")
        assert p2["baseProduct"]["product"][0]["action"] == "ADD"


# ── subscriber_inquiry needs no account ID ───────────────────────────
class TestSubscriberInquiryNeedsNoAccountId:
    """subscriber_inquiry never required an account ID.

    This class previously asserted that the call was "disabled until an account
    ID exists". That gate was our own invention — the vendor contract identifies
    the subscriber by msisdn / iccid / imsi and has no account-id field at all,
    so the absence of an account ID is simply not an error. What DOES stop the
    call today is the client's fail-closed boundary: subscriber_inquiry is not
    yet cleared for live sending.
    """

    @pytest.mark.asyncio
    async def test_missing_account_id_is_not_what_stops_the_call(self, tmobile_env):
        """No account ID configured, and the refusal is the live-send boundary.

        Changed because the account-id requirement was never in the vendor
        contract; the error that remains is the certification gate, not a
        missing account.
        """
        client = taap.TMobileTAAPClient()  # TMOBILE_ACCOUNT_ID == ""
        with pytest.raises(ops.TMobileOperationBlockedError) as exc:
            await client.subscriber_inquiry("5550001234")
        assert "account" not in str(exc.value).lower()
        assert "subscriber_inquiry" in str(exc.value)
        await client.close()

    @pytest.mark.asyncio
    async def test_identifier_is_required(self, tmobile_env):
        """An identifier — not an account ID — is the one mandatory input."""
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="msisdn, iccid, or imsi"):
            await client.subscriber_inquiry()
        await client.close()


# ── callback account-ID capture (pure) ───────────────────────────────
class TestAccountIdCapture:
    def _payload(self, body):
        return SimpleNamespace(
            headers={"x-true911-tmobile-event-type": "provisioning"},
            body=body,
            created_at=datetime(2026, 6, 1, tzinfo=timezone.utc),
        )

    def test_extract_signal_picks_up_account_id(self):
        sig = extract_signal(self._payload({
            "ICCID": "8901240204219433645",
            "accountId": "ACC-789",
            "msisdn": "7542697860",
        }))
        assert sig.account_id == "ACC-789"
        assert sig.iccid == "8901240204219433645"
        assert sig.msisdn == "7542697860"

    def test_extract_signal_account_id_absent(self):
        sig = extract_signal(self._payload({"ICCID": "8901240204219433645"}))
        assert sig.account_id is None

    def test_extract_signal_alternate_account_key(self):
        sig = extract_signal(self._payload({"subscriber_account_id": "ACC-XYZ"}))
        assert sig.account_id == "ACC-XYZ"

    def test_merge_stores_account_and_msisdn(self):
        meta = merge_activation_identifiers({"volte_enabled": True}, "ACC-1", "7542697860")
        assert meta["tmobile_account_id"] == "ACC-1"
        assert meta["tmobile_msisdn"] == "7542697860"
        assert meta["volte_enabled"] is True  # existing keys preserved

    def test_merge_is_noop_without_account_id(self):
        meta = merge_activation_identifiers(None, None, None)
        assert meta == {}
