"""Tests for the T-Mobile activation-first flow.

Covers:
  * activate_subscriber() builds the correct activation payload
    (marketZIP + ICCID + productId) with NO accountId and NO msisdn,
    sends the call-back-location header, and falls back to env.
  * activate_subscriber() validates required inputs.
  * subscriber_inquiry() is disabled until an account ID exists.
  * the callback processor captures a generated account ID + assigned
    MSISDN (pure helpers — no DB, per the house test pattern).

No real T-Mobile credentials: the RSA key is generated and HTTP is mocked.
OAuth/PoP code is exercised but not modified.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from types import SimpleNamespace

import httpx
import pytest
import respx
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

import app.integrations.tmobile_taap as taap
from app.services.tmobile_callback_processor import (
    extract_signal,
    merge_activation_identifiers,
)

TOKEN_URL = "https://pit-oauth.t-mobile.com/oauth2/v2/tokens"
BASE_URL = "https://pit-apis.t-mobile.com"
# Default subscriber base path is the PIT gateway's /wholesale/v1/subscriber.
ACTIVATE_PATH = "/wholesale/v1/subscriber/activate"
ACTIVATE_URL = f"{BASE_URL}{ACTIVATE_PATH}"


@pytest.fixture
def tmobile_env(monkeypatch):
    """Generated RSA key + mocked T-Mobile settings (creds, hosts, activation env)."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    monkeypatch.setattr(taap, "_load_private_key", lambda: pem)
    for name, value in {
        "TMOBILE_ENV": "pit",
        "TMOBILE_BASE_URL": BASE_URL,
        "TMOBILE_TOKEN_URL": TOKEN_URL,
        "TMOBILE_CONSUMER_KEY": "ck",
        "TMOBILE_CONSUMER_SECRET": "cs",
        "TMOBILE_PARTNER_ID": "128",
        "TMOBILE_SENDER_ID": "128",
        "TMOBILE_ACCOUNT_ID": "",          # not available yet — generated by activation
        "TMOBILE_PRODUCT_ID": "PID-ENV",
        "TMOBILE_MARKET_ZIP": "30338",
        "TMOBILE_CALLBACK_LOCATION": "https://pit-api.example.com/tmobile/wholesale/callback",
    }.items():
        monkeypatch.setattr(f"app.config.settings.{name}", value)


def _mock_token_and_activate():
    respx.post(TOKEN_URL).mock(return_value=httpx.Response(
        200, json={"access_token": "tok", "expires_in": 3600}))
    respx.post(ACTIVATE_URL).mock(return_value=httpx.Response(
        200, json={"status": "accepted"}))


def _activate_request(path: str = ACTIVATE_PATH):
    for call in respx.calls:
        if call.request.url.path == path:
            return call.request
    raise AssertionError("activation request was not sent")


# ── activate_subscriber payload / headers ────────────────────────────
class TestActivateSubscriber:
    @respx.mock
    @pytest.mark.asyncio
    async def test_payload_has_no_accountid_or_msisdn(self, tmobile_env):
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(
            iccid="8901240204219433645", market_zip="30346",
            product_id="PID-1", callback_location="https://cb.example/hook")
        await client.close()

        req = _activate_request()
        body = json.loads(req.content)
        assert body == {"marketZIP": "30346", "ICCID": "8901240204219433645",
                        "productId": "PID-1"}
        assert "accountId" not in body
        assert "msisdn" not in body
        assert req.headers["call-back-location"] == "https://cb.example/hook"
        # Infatrac sender/partner = 128 (applied by _request from env).
        assert req.headers["X-Sender-Id"] == "128"
        assert req.headers["X-Partner-Id"] == "128"
        # No account header while account ID is unknown.
        assert "X-Account-Id" not in req.headers

    @respx.mock
    @pytest.mark.asyncio
    async def test_falls_back_to_env(self, tmobile_env):
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(iccid="8901240204219433652")
        await client.close()

        req = _activate_request()
        body = json.loads(req.content)
        assert body["marketZIP"] == "30338"        # TMOBILE_MARKET_ZIP
        assert body["productId"] == "PID-ENV"      # TMOBILE_PRODUCT_ID
        assert req.headers["call-back-location"].endswith("/tmobile/wholesale/callback")

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_iccid(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="ICCID"):
            await client.activate_subscriber(iccid="")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_product_id(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_PRODUCT_ID", "")
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="productId"):
            await client.activate_subscriber(iccid="89012", market_zip="30338", product_id="")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_market_zip(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_MARKET_ZIP", "")
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="marketZIP"):
            await client.activate_subscriber(iccid="89012", market_zip="", product_id="PID-1")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_requires_callback_location(self, tmobile_env, monkeypatch):
        # The account ID comes back ONLY via the callback — activation must
        # refuse to send without one rather than strand the generated ID.
        monkeypatch.setattr("app.config.settings.TMOBILE_CALLBACK_LOCATION", "")
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="call-back-location"):
            await client.activate_subscriber(
                iccid="8901240204219433645", market_zip="30346",
                product_id="PID-1", callback_location="")
        await client.close()

    @respx.mock
    @pytest.mark.asyncio
    async def test_callback_location_on_wire(self, tmobile_env):
        _mock_token_and_activate()
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(
            iccid="8901240204219433645", market_zip="30346",
            product_id="PID-1", callback_location="  https://cb.example/hook  ")
        await client.close()
        req = _activate_request()
        # Required header is present and stripped of stray whitespace.
        assert req.headers["call-back-location"] == "https://cb.example/hook"


# ── env-driven resource paths ────────────────────────────────────────
class TestEnvDrivenPaths:
    def test_default_subscriber_base_is_v1(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        # PIT gateway URL list uses /wholesale/v1/subscriber (not subscriber/v2).
        assert client.subscriber_base_path == "/wholesale/v1/subscriber"
        assert client.activation_endpoint() == "/wholesale/v1/subscriber/activate"
        assert client._subscriber_path("inquiry") == "/wholesale/v1/subscriber/inquiry"

    def test_activation_path_env_override(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_ACTIVATION_PATH",
                            "/wholesale/v1/activation/submit")
        client = taap.TMobileTAAPClient()
        # Explicit activation override wins; subscriber base is unaffected.
        assert client.activation_endpoint() == "/wholesale/v1/activation/submit"
        assert client._subscriber_path("inquiry") == "/wholesale/v1/subscriber/inquiry"

    def test_subscriber_base_env_override_changes_derived_activate(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_SUBSCRIBER_BASE_PATH",
                            "/wholesale/subscriber/v2")
        client = taap.TMobileTAAPClient()
        # No explicit activation override -> derived from the (overridden) base.
        assert client.activation_endpoint() == "/wholesale/subscriber/v2/activate"

    def test_trailing_slash_is_normalized(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_SUBSCRIBER_BASE_PATH",
                            "/wholesale/v1/subscriber/")
        client = taap.TMobileTAAPClient()
        assert client._subscriber_path("activate") == "/wholesale/v1/subscriber/activate"

    @respx.mock
    @pytest.mark.asyncio
    async def test_activation_uses_override_path_on_wire(self, tmobile_env, monkeypatch):
        monkeypatch.setattr("app.config.settings.TMOBILE_ACTIVATION_PATH",
                            "/wholesale/v1/activation/submit")
        respx.post(TOKEN_URL).mock(return_value=httpx.Response(
            200, json={"access_token": "tok", "expires_in": 3600}))
        respx.post(f"{BASE_URL}/wholesale/v1/activation/submit").mock(
            return_value=httpx.Response(200, json={"status": "accepted"}))
        client = taap.TMobileTAAPClient()
        await client.activate_subscriber(iccid="8901240204219433645",
                                         market_zip="30346", product_id="PID-1")
        await client.close()
        req = _activate_request("/wholesale/v1/activation/submit")
        assert json.loads(req.content)["ICCID"] == "8901240204219433645"


# ── dry-run preview (no network, redacted secrets) ───────────────────
class TestActivationPreview:
    def test_preview_payload_and_safe_headers(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(
            iccid="8901260963132697538", market_zip="30346",
            product_id="wps-00011586",
            callback_location="https://cb.example/hook")

        assert preview["method"] == "POST"
        assert preview["would_send"] is False
        assert preview["path"] == "/wholesale/v1/subscriber/activate"
        assert preview["url"].endswith("/wholesale/v1/subscriber/activate")
        assert preview["payload"] == {
            "marketZIP": "30346", "ICCID": "8901260963132697538",
            "productId": "wps-00011586",
        }
        # Secret-bearing headers must be redacted placeholders, never real values.
        assert "redacted" in preview["headers"]["Authorization"].lower()
        assert "redacted" in preview["headers"]["X-Authorization"].lower()
        assert "Bearer " not in preview["headers"]["Authorization"]
        # Non-sensitive headers are real.
        assert preview["headers"]["X-Sender-Id"] == "128"
        assert preview["headers"]["X-Partner-Id"] == "128"
        assert preview["headers"]["call-back-location"] == "https://cb.example/hook"

    def test_preview_falls_back_to_env(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(iccid="8901260963132697538")
        assert preview["payload"]["marketZIP"] == "30338"   # TMOBILE_MARKET_ZIP
        assert preview["payload"]["productId"] == "PID-ENV"  # TMOBILE_PRODUCT_ID

    def test_preview_validates_inputs(self, tmobile_env):
        client = taap.TMobileTAAPClient()
        with pytest.raises(ValueError, match="ICCID"):
            client.build_activation_preview(iccid="")

    def test_preview_surfaces_missing_callback(self, tmobile_env, monkeypatch):
        # Dry-run must SHOW the gap, not raise — it's how operators detect a
        # missing callback before going live.
        monkeypatch.setattr("app.config.settings.TMOBILE_CALLBACK_LOCATION", "")
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(
            iccid="8901260963132697538", product_id="wps-00011586")
        assert preview["callback_location_configured"] is False
        assert "call-back-location" in preview["headers"]
        assert "NOT SET" in preview["headers"]["call-back-location"]
        assert any("call-back-location is NOT configured" in n for n in preview["notes"])

    def test_preview_shows_configured_callback(self, tmobile_env):
        client = taap.TMobileTAAPClient()  # fixture sets TMOBILE_CALLBACK_LOCATION
        preview = client.build_activation_preview(
            iccid="8901260963132697538", product_id="wps-00011586")
        assert preview["callback_location_configured"] is True
        assert preview["headers"]["call-back-location"].endswith("/tmobile/wholesale/callback")
        assert not any("NOT configured" in n for n in preview["notes"])

    def test_preview_makes_no_http_calls(self, tmobile_env):
        # respx is NOT active here; if the preview opened a socket this would
        # hit the network. It must stay purely local.
        client = taap.TMobileTAAPClient()
        preview = client.build_activation_preview(
            iccid="8901260963132697538", product_id="wps-00011586")
        assert preview["would_send"] is False


# ── subscriber_inquiry gated on account ID ───────────────────────────
class TestSubscriberInquiryGate:
    @pytest.mark.asyncio
    async def test_disabled_without_account_id(self, tmobile_env):
        client = taap.TMobileTAAPClient()  # TMOBILE_ACCOUNT_ID == ""
        with pytest.raises(RuntimeError, match="disabled until an account ID"):
            await client.subscriber_inquiry("7542697860")
        await client.close()


# ── callback account-ID capture (pure) ───────────────────────────────
class TestAccountIdCapture:
    def _payload(self, body):
        return SimpleNamespace(
            headers={"x-true911-tmobile-event-type": "provisioning"},
            body=body,
            created_at=datetime(2026, 6, 1, tzinfo=timezone.utc),
        )

    def test_extract_signal_picks_up_account_id(self):
        sig = extract_signal(self._payload({
            "ICCID": "8901240204219433645",
            "accountId": "ACC-789",
            "msisdn": "7542697860",
        }))
        assert sig.account_id == "ACC-789"
        assert sig.iccid == "8901240204219433645"
        assert sig.msisdn == "7542697860"

    def test_extract_signal_account_id_absent(self):
        sig = extract_signal(self._payload({"ICCID": "8901240204219433645"}))
        assert sig.account_id is None

    def test_extract_signal_alternate_account_key(self):
        sig = extract_signal(self._payload({"subscriber_account_id": "ACC-XYZ"}))
        assert sig.account_id == "ACC-XYZ"

    def test_merge_stores_account_and_msisdn(self):
        meta = merge_activation_identifiers({"volte_enabled": True}, "ACC-1", "7542697860")
        assert meta["tmobile_account_id"] == "ACC-1"
        assert meta["tmobile_msisdn"] == "7542697860"
        assert meta["volte_enabled"] is True  # existing keys preserved

    def test_merge_is_noop_without_account_id(self):
        meta = merge_activation_identifiers(None, None, None)
        assert meta == {}
