"""T-Mobile activation lifecycle — pure state + timestamp tracking.

The account ID is generated by T-Mobile's activation, not supplied by us, so an
activation moves through states driven partly by our submit and partly by the
async callback.  This module is pure (no DB, no I/O): it transforms a small
"activation record" dict that the caller persists on ``Sim.meta`` under the key
``tmobile_activation``.

States:
    Pending Activation  -> Activation Submitted -> Activation Processing
                        -> Activated | Activation Failed

Record shape::

    {
      "state": "<one of the states>",
      "requested_at":  <iso|null>,   # when WE submitted the activation
      "callback_at":   <iso|null>,   # when the activation callback arrived
      "account_id":    <str|null>,   # generated by activation
      "msisdn":        <str|null>,   # assigned by activation
      "activation_status": <str|null>,  # vendor's raw status string
      "failure_reason": <str|null>,
    }
"""

from __future__ import annotations

from enum import Enum
from typing import Optional


class ActivationState(str, Enum):
    PENDING = "Pending Activation"
    SUBMITTED = "Activation Submitted"
    PROCESSING = "Activation Processing"
    ACTIVATED = "Activated"
    FAILED = "Activation Failed"


META_KEY = "tmobile_activation"

# Vendor status strings (lowercased) that resolve to a terminal outcome.
SUCCESS_STATUSES = frozenset({
    "active", "activated", "complete", "completed", "success", "provisioned",
})
FAILURE_STATUSES = frozenset({
    "failed", "failure", "error", "rejected", "declined", "cancelled", "canceled",
})

# Forward transitions enforced for our own submit path.  Terminal outcomes from
# the vendor (Activated / Failed) are always accepted regardless of prior state
# because the callback is authoritative — activation can happen out of band.
_ALLOWED: dict[ActivationState, set[ActivationState]] = {
    ActivationState.PENDING: {ActivationState.SUBMITTED, ActivationState.FAILED},
    ActivationState.SUBMITTED: {ActivationState.PROCESSING, ActivationState.ACTIVATED, ActivationState.FAILED},
    ActivationState.PROCESSING: {ActivationState.ACTIVATED, ActivationState.FAILED},
    ActivationState.ACTIVATED: set(),
    ActivationState.FAILED: {ActivationState.SUBMITTED},  # allow retry
}


def can_transition(frm: ActivationState, to: ActivationState) -> bool:
    return to in _ALLOWED.get(frm, set())


def new_record(*, requested_at: Optional[str] = None) -> dict:
    return {
        "state": ActivationState.PENDING.value,
        "requested_at": requested_at,
        "callback_at": None,
        "account_id": None,
        "msisdn": None,
        "activation_status": None,
        "failure_reason": None,
    }


def state_of(record: Optional[dict]) -> ActivationState:
    if not record:
        return ActivationState.PENDING
    try:
        return ActivationState(record.get("state", ActivationState.PENDING.value))
    except ValueError:
        return ActivationState.PENDING


def _with(record: Optional[dict], **changes) -> dict:
    out = dict(record or new_record())
    out.update(changes)
    return out


def mark_submitted(record: Optional[dict], *, at: str) -> dict:
    """Record that WE submitted the activation request (sets requested_at)."""
    return _with(record, state=ActivationState.SUBMITTED.value, requested_at=at)


def mark_processing(record: Optional[dict], *, at: str,
                    activation_status: Optional[str] = None) -> dict:
    return _with(record, state=ActivationState.PROCESSING.value,
                 callback_at=at, activation_status=activation_status)


def mark_activated(record: Optional[dict], *, account_id: Optional[str],
                   msisdn: Optional[str], at: str,
                   activation_status: Optional[str] = None) -> dict:
    """Terminal success — always accepted (the callback is authoritative)."""
    base = dict(record or new_record())
    if account_id:
        base["account_id"] = account_id
    if msisdn:
        base["msisdn"] = msisdn
    base["state"] = ActivationState.ACTIVATED.value
    base["callback_at"] = at
    base["activation_status"] = activation_status
    base["failure_reason"] = None
    return base


def mark_failed(record: Optional[dict], *, reason: Optional[str], at: str,
                activation_status: Optional[str] = None) -> dict:
    return _with(record, state=ActivationState.FAILED.value, callback_at=at,
                 activation_status=activation_status, failure_reason=reason)


def resolve_from_callback(
    record: Optional[dict],
    *,
    account_id: Optional[str],
    msisdn: Optional[str],
    activation_status: Optional[str],
    at: str,
) -> dict:
    """Apply a callback's outcome to the activation record.

    - account_id present (or an explicit success status) -> Activated
    - explicit failure status                            -> Activation Failed
    - any other non-empty status                         -> Activation Processing
    - nothing actionable                                 -> record unchanged
    """
    status_l = (activation_status or "").strip().lower()
    if account_id or status_l in SUCCESS_STATUSES:
        return mark_activated(record, account_id=account_id, msisdn=msisdn,
                              at=at, activation_status=activation_status)
    if status_l in FAILURE_STATUSES:
        return mark_failed(record, reason=activation_status, at=at,
                           activation_status=activation_status)
    if status_l:
        return mark_processing(record, at=at, activation_status=activation_status)
    return dict(record or new_record())
