"""Resolve the per-ICCID T-Mobile account ID and drive QuerySubscriber.

Background
==========
The activation-first flow generates the T-Mobile account ID asynchronously and
delivers it on the provisioning callback, where
``tmobile_callback_processor`` captures it onto ``sims.meta`` (keyed on the
globally-unique ``Sim.iccid``).  This module is the read-back side: given an
ICCID it resolves the STORED per-subscriber account ID + MSISDN and calls
``TMobileTAAPClient.subscriber_inquiry`` with them — so SubscriberInquiry uses
the right account ID for that specific ICCID instead of a single global env var.

Safety
======
``query_subscriber_by_iccid`` is a LIVE T-Mobile call, so it is gated behind
``TMOBILE_PIT_LIVE_CALLS_ENABLED`` exactly like ``activate_subscriber`` — it
refuses to send (raises ``RuntimeError``) unless the flag is explicitly on.
Pure resolution (``stored_account_id_for_iccid``) never makes a network call and
is not gated.

No secrets are logged: this module only ever handles the account ID / MSISDN
(non-secret identifiers) and never touches consumer keys, tokens, or the
Authorization header.
"""

from __future__ import annotations

import logging
from typing import Any, Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.integrations.tmobile_taap import TMobileTAAPClient
from app.models.sim import Sim
from app.services import tmobile_activation as activation

logger = logging.getLogger("true911.tmobile.subscriber")

# Flat key written by ``merge_activation_identifiers`` on ``sims.meta``.
ACCOUNT_ID_META_KEY = "tmobile_account_id"
MSISDN_META_KEY = "tmobile_msisdn"


def account_id_from_sim(sim: Sim) -> Optional[str]:
    """Return the stored T-Mobile account ID for a Sim, or ``None``.

    Prefers the flat ``sims.meta.tmobile_account_id`` written at capture time;
    falls back to the account ID inside the ``tmobile_activation`` lifecycle
    record.  Both are written by the callback processor — the flat key is the
    canonical one, the record is the redundant copy.
    """
    meta = sim.meta or {}
    flat = meta.get(ACCOUNT_ID_META_KEY)
    if flat:
        return str(flat)
    record = meta.get(activation.META_KEY) or {}
    nested = record.get("account_id")
    return str(nested) if nested else None


def msisdn_from_sim(sim: Sim) -> Optional[str]:
    """Return the activation-assigned MSISDN, else the Sim's own MSISDN."""
    meta = sim.meta or {}
    assigned = meta.get(MSISDN_META_KEY)
    if assigned:
        return str(assigned)
    return sim.msisdn or None


async def _load_sim_by_iccid(db: AsyncSession, iccid: str) -> Optional[Sim]:
    # ``Sim.iccid`` is globally unique → 0 or 1 row, never ambiguous.
    q = select(Sim).where(Sim.iccid == iccid)
    return (await db.execute(q)).scalar_one_or_none()


async def stored_account_id_for_iccid(
    db: AsyncSession, iccid: str
) -> Optional[str]:
    """Resolve the stored per-ICCID account ID without any network call."""
    if not iccid:
        return None
    sim = await _load_sim_by_iccid(db, iccid)
    if sim is None:
        return None
    return account_id_from_sim(sim)


async def query_subscriber_by_iccid(
    db: AsyncSession,
    iccid: str,
    *,
    client: Optional[TMobileTAAPClient] = None,
) -> dict[str, Any]:
    """Run SubscriberInquiry for an ICCID using its STORED account ID.

    Resolves account ID + MSISDN from the matched ``sims`` row and calls
    ``subscriber_inquiry``.  LIVE call — gated behind
    ``TMOBILE_PIT_LIVE_CALLS_ENABLED``.

    Raises:
        RuntimeError: live calls disabled, or no account ID has been captured
            for this ICCID yet (activation callback hasn't arrived).
        ValueError:   no Sim for the ICCID, or no MSISDN to query with.
    """
    # Guard: refuse to make a real call unless explicitly authorized.
    if not TMobileTAAPClient.live_calls_enabled():
        raise RuntimeError(
            "Live T-Mobile PIT calls are DISABLED — SubscriberInquiry not sent. "
            "Set TMOBILE_PIT_LIVE_CALLS_ENABLED=true to authorize real PIT calls."
        )

    if not iccid:
        raise ValueError("query_subscriber_by_iccid requires an ICCID")

    sim = await _load_sim_by_iccid(db, iccid)
    if sim is None:
        raise ValueError(
            f"No Sim found for ICCID {_redact(iccid)}; cannot resolve the "
            "subscriber context for SubscriberInquiry."
        )

    account_id = account_id_from_sim(sim)
    if not account_id:
        raise RuntimeError(
            f"No T-Mobile account ID stored for ICCID {_redact(iccid)} yet — "
            "the activation callback has not captured one. SubscriberInquiry "
            "requires the account ID generated by activation."
        )

    msisdn = msisdn_from_sim(sim)
    if not msisdn:
        raise ValueError(
            f"No MSISDN available for ICCID {_redact(iccid)}; SubscriberInquiry "
            "requires an MSISDN."
        )

    own_client = client or TMobileTAAPClient()
    try:
        logger.info(
            "T-Mobile SubscriberInquiry by ICCID %s (using stored per-ICCID "
            "account id)",
            _redact(iccid),
        )
        return await own_client.subscriber_inquiry(msisdn, account_id=account_id)
    finally:
        # Only close a client we created ourselves.
        if client is None:
            await own_client.close()


def _redact(value: Optional[str]) -> str:
    """Render an ICCID for logs without leaking the full value."""
    if not value:
        return "<none>"
    if len(value) <= 8:
        return value[0] + "***"
    return f"{value[:6]}...{value[-2:]}"
